### ISSUE TITLE
Objective 01: HLS-VI

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/SNWG-MO-PI-Objectives#44]
## Description
Prepare for HLS-VI Formulation to Implementation Decision Gate

### Acceptance Criteria:

- [ ] Finalize Project plan
- - [ ] Updated budget numbers
- - [ ]  Open Science Data Management Plan (OSDMP)
- [ ] ESDIS/DAAC agreement in place (external dep)
- [x] Schedule Formulation to Implementation Decision Gate (to hold in future PI)

Dependencies:
- HLS-VI team for project plan updates
- ESDIS to complete DAAC selection & ESDIS/DAAC/HLS-VI to set up agreements (IPA w/ ESDIS and ICD w/ DAAC)
Risks
- ESDIS staffing complications may delay DAAC progress

**Comment by Jeanne-le-Roux** [comment]
Update from ESDIS on 4/24/23: DAAC is finalizing budget proposal for HLS-VI. Once complete, the DAAC selection will be sent to HQ for approval.

**Comment by CherrelleTucker** [comment]
[2023-05-22 SNWG-NASA Monthly Meeting](https://docs.google.com/document/d/1vPsOp4tMX_vlewqAXAqsEsUWQ-_w-W_18D9Y2DePAE8/edit#heading=h.siwey4ill55g)

Pending DAAC assignments:

HLS-VI (HLS – Vegetation Indices) - LP.DAAC
PBL (Merged Planetary Boundary Layer) - GES DISC
Awaiting final designation for the above products. Cerese is in conversations re: a DAAC selection memo.
