### ISSUE TITLE
Objective 11: SNWG MO (Templates)

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/SNWG-MO-PI-Objectives#52]
## Description
Develop the following SNWG MO templates that supports the project lifecycle

### Acceptance Criteria:
- [ ] Document sunsetting/transition criteria for SNWG Projects
- [ ] Draft document transition plans for cycle 1 projects
- - [ ] ADMG/CASEI to ESDS/ESDIS
- - [ ] DCD to merge with SNWG MO Assessment and SEP
- _Stretch goal_: ORR Decision Memorandum Template drafted and approved
- _Stretch goal_: Continuation Assessment(s) (CAs) Decision Memorandum Template drafted and approved
- _Stretch goal_: Project Closeout DG Decision Memorandum Template drafted and approved

### Dependencies
- Official sunsetting criteria pending HQ and OMB approval and communication
- Transition plans may need external input from management

### Risks
None currently identified

**Comment by Jeanne-le-Roux** [comment]
Started some brainstorming on transition plans [in this doc](https://docs.google.com/document/d/17yw-sRmhcssZbR8b9mQTJvM-iHgNBJsRBsPJQCnygVk/edit#).

**Comment by Jeanne-le-Roux** [comment]
Stretch goal: Project Closeout DG Decision Memorandum Template drafted and approved

Project Closeout DG Decision Memo template [drafted here.](https://docs.google.com/document/d/1pxWhJD_ElH2FzLCyL6O_mWZZhc3D7wzY-H19_IRlsiQ/edit#)
