### ISSUE TITLE
Objective 12: SNWG MO (Program Plan)

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/SNWG-MO-PI-Objectives#53]
## Description
Finalize and Baseline the SNWG MO Program Plan (v1.0)

### Acceptance Criteria:

- [x] ESDS-sponsor review and approval of the Draft SNWG MO Program Plan
- - Note: mostly complete, pending final decision on ORR roles and responsibilities.  
- [x] Baselined Program Plan uploaded to Sharepoint

### Dependencies
ESDS-sponsor for approval

### Risks
None currently identified

**Comment by CherrelleTucker** [comment]
From: le Roux, Jeanné (MSFC-ST11)[UAH]
Sent: Friday, May 19, 2023 3:09 PM
To: Ostrenga, Dana M. (GSFC-4230) <[dana.ostrenga@nasa.gov](mailto:dana.ostrenga@nasa.gov)>; Rice, Justin L. (GSFC-5860) <[justin.l.rice@nasa.gov](mailto:justin.l.rice@nasa.gov)>; Michael, Karen A. (GSFC-5860) <[karen.a.michael@nasa.gov](mailto:karen.a.michael@nasa.gov)>
Cc: Albers, Cerese {HQ} (MSFC-DK000) <[cerese.m.albers@nasa.gov](mailto:cerese.m.albers@nasa.gov)>; Sobchak, Ted C. (GSFC-4590) <[ted.c.sobchak@nasa.gov](mailto:ted.c.sobchak@nasa.gov)>; Gregory, Sean P. (MSFC-ST14) <[sean.p.gregory@nasa.gov](mailto:sean.p.gregory@nasa.gov)>; Hill, Larry (MSFC-ST14)[Consolidated Program Support Services (CPSS PP&C)] <[larry.hill@nasa.gov](mailto:larry.hill@nasa.gov)>
Subject: SNWG MO Program Plan Sign Off & ORR Discussion 
 
Hello Dana, Justin and Karen, 
 
I am reaching out on behalf of the SNWG Management Office (MO). We are currently driving to get the SNWG MO Program Plan signed and finalized as soon as possible so that we can move forward with initiating new project contracts. As you are probably aware, some (but not all) of the projects coming out of the SNWG process will produce new data products to be archived at a DAAC. We’d like to get your concurrence on the language in the program plan pertaining to ESDIS’s involvement in the SNWG process. I’ll link below the specific sections of the program plan that are relevant. (You all should have comment access but let me know if you have any issues). 
 
One key touchpoint that we’d like your concurrence on are expectations pertaining to an ORR for data products prior to going operational at a DAAC. Essentially we’re proposing that the SNWG MO convene the ORR with participation from ESDIS and the DAAC to ensure DAAC preparedness. We’d be happy to meet ASAP to further discuss expectations. The language in the program plan is fairly high level so we’d like to get your agreement on that first and foremost and then we can collaborate on the specifics. We’re requiring an ORR for all projects with an operational component, and having ESDIS involvement will be key to a successful review. Here are the program plan sections: 
 
•	[Section 3.1](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.1ruyx6d0to2l&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7C07ab13e8e00c41f604b108db58a61199%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638201242504051701%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rtV0kPFkdHbe%2BD2hL0XJw74B5V1u4Nbsh1wEMRo%2BVa8%3D&reserved=0) (lists ESDIS and the DAACs as SNWG MO stakeholders) 
•	[Section 5.1.2.3](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.7vh1tc7z9f9v&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7C07ab13e8e00c41f604b108db58a61199%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638201242504051701%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HW5Lx8QVS7HW7YGaDFBVbt0N4dDBDINOvu%2BTfMKicyg%3D&reserved=0) (Requirement III only) 
•	[Section 6.1](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.yo3q9tl74wf7&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7C07ab13e8e00c41f604b108db58a61199%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638201242504051701%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yS252FOFWp6Ub186Zemgl3KLvv4AGt%2BN5l45FNYAR%2FE%3D&reserved=0) (notes that ESDIS supports cost estimation efforts during the Assessment phase) 
•	[Section 6.2.1](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.c8kzoiv2i9x0&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7C07ab13e8e00c41f604b108db58a61199%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638201242504051701%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=L%2FQguDBUeTc9NDBc%2B3mFmMTwCr%2BpFcXxj6hfUFWM%2BnQ%3D&reserved=0) (describes the DAAC selection process) 
•	[Section 12.1.3](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.e7vibarxsbv&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7C07ab13e8e00c41f604b108db58a61199%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638201242504051701%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ISXe%2Fy5OVFa7g3Piy53feBb%2BKkvSbHbEmXZxrVEh2Qg%3D&reserved=0) (describes the Assessment phase. Mention of ESDIS cost estimation support.) 
•	[Section 12.2.2.1](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.sp5ax9onn9pt&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7C07ab13e8e00c41f604b108db58a61199%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638201242504051701%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=wk9Mykp6oCfsImDb0Zd5MfXrauSqzi1BzOVUOKScO3A%3D&reserved=0) (re-iterates DAAC selection step and agreement types w/ ESDIS/DAACs) 
•	[Section 12.2.2.3](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.2q10ulif3uso&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7C07ab13e8e00c41f604b108db58a61199%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638201242504051701%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=51Vpz56X%2F2zESH3XNW66kp9OwPZ8c%2B4rabHRzPAaS7I%3D&reserved=0) (Formulation to Implementation Decision Gate review – if data goes to a DAAC, an ESDIS & DAAC representative will be invited to this review. At this point the DAAC selection and any agreements with ESDIS/DAACs should be completed.) 
•	[Section 12.2.3.1.4](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.4c3bur2rcgw6&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7C07ab13e8e00c41f604b108db58a61199%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638201242504051701%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=jcSg4ouf7stzVNKAGLK88PFCkWs7dRA6N4TKnHVStaQ%3D&reserved=0) (describes the ORR – also recommend reading [Section 12.2.3.1.3](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.mh1i02nkpeyr&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7C07ab13e8e00c41f604b108db58a61199%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638201242504051701%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=VgSUk%2BL6IxySMvWTwTfC1YWTMzxk9Y9%2FrpcAdnYdEQU%3D&reserved=0) right before) ** this is a key touchpoint we’d like to discuss ASAP   
•	[Section 12.2.4.2](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.ahueog70qipv&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7C07ab13e8e00c41f604b108db58a61199%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638201242504051701%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=I51L%2BKFhduPiI%2F1Fc1Tuda05FJx3kMULi3BbOrE5eFU%3D&reserved=0) (describes project closeout – if data goes to a DAAC, an ESDIS & DAAC representative will be invited to participate in the closeout review) 
•	[Appendix D](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.bzt20h47l9gr&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7C07ab13e8e00c41f604b108db58a61199%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638201242504051701%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=N1iAE%2BLX2%2FLkACWQg6PYeFCSyfjqoSpmDBP30k9dYP8%3D&reserved=0) (signature authorities for agreements w/ ESIDS. This list is based on the OPERA IPA/ICDs so please let us know if these are not the correct personnel.) 
•	[Appendix F](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.l0yrhiwbqq3t&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7C07ab13e8e00c41f604b108db58a61199%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638201242504051701%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=99AC3BWxURxd0qW4Sf2tV0iIfcSgwuLqaxO0URISAVE%3D&reserved=0) (DAAC table & re-iterates that ESDIS carries out the DAAC selection process) 
Cc’d is Sean Gregory who is the SNWG MO PM and Larry Hill who also provides management support to the SNWG MO.  
 
Thank you! 
 
Jeanné le Roux 
SNWG MO Systems Engineer | NASA MSFC [IMPACT](https://earthdata.nasa.gov/esds/impact)  
The University of Alabama in Huntsville 
Cramer Research Hall/NSSTC 3079

**Comment by Jeanne-le-Roux** [comment]
Dana said she would review the Program Plan and leave her comments by COB Wednesday May 24th.

**Comment by CherrelleTucker** [comment]
From: le Roux, Jeanné (MSFC-ST11)[UAH] <jeanne.leroux@nasa.gov> 
Sent: Friday, May 26, 2023 10:24 AM
To: Tucker, Cherrelle J. (MSFC-ST11)[Consolidated Program Support Services] <cherrelle.j.tucker@nasa.gov>
Subject: Fw: SNWG MO Program Plan Sign Off & ORR Discussion 

Forgot to forward this to you - luckily ESDIS had minimal edits to the program plan which have already been addressed. All we're waiting on now is Cerese's signature/HQ approval (which will hopefully happen quickly once she's back in the office). 

________________________________________
From: le Roux, Jeanné (MSFC-ST11)[UAH] <[jeanne.leroux@nasa.gov](mailto:jeanne.leroux@nasa.gov)>
Sent: Friday, May 26, 2023 10:06 AM
To: Ostrenga, Dana M. (GSFC-4230) <[dana.ostrenga@nasa.gov](mailto:dana.ostrenga@nasa.gov)>; Rice, Justin L. (GSFC-5860) <[justin.l.rice@nasa.gov](mailto:justin.l.rice@nasa.gov)>; Michael, Karen A. (GSFC-5860) <[karen.a.michael@nasa.gov](mailto:karen.a.michael@nasa.gov)>
Cc: Albers, Cerese {HQ} (MSFC-DK000) <[cerese.m.albers@nasa.gov](mailto:cerese.m.albers@nasa.gov)>; Sobchak, Ted C. (GSFC-4590) <[ted.c.sobchak@nasa.gov](mailto:ted.c.sobchak@nasa.gov)>; Gregory, Sean P. (MSFC-ST14) <[sean.p.gregory@nasa.gov](mailto:sean.p.gregory@nasa.gov)>; Hill, Larry (MSFC-ST14)[Consolidated Program Support Services (CPSS PP&C)] <[larry.hill@nasa.gov](mailto:larry.hill@nasa.gov)>
Subject: Re: SNWG MO Program Plan Sign Off & ORR Discussion 
 
Dana,

Thank you for your feedback! I updated the table in Appendix D if you want to take another look at it. 

We will be in touch as we work through this process for the Cycle 3 solutions. 

Wishing everyone a relaxing holiday weekend.

--
Jeanné
________________________________________
From: Ostrenga, Dana M. (GSFC-4230) <[dana.ostrenga@nasa.gov](mailto:dana.ostrenga@nasa.gov)>
Sent: Thursday, May 25, 2023 11:57 AM
To: le Roux, Jeanné (MSFC-ST11)[UAH] <[jeanne.leroux@nasa.gov](mailto:jeanne.leroux@nasa.gov)>; Rice, Justin L. (GSFC-5860) <[justin.l.rice@nasa.gov](mailto:justin.l.rice@nasa.gov)>; Michael, Karen A. (GSFC-5860) <[karen.a.michael@nasa.gov](mailto:karen.a.michael@nasa.gov)>
Cc: Albers, Cerese {HQ} (MSFC-DK000) <[cerese.m.albers@nasa.gov](mailto:cerese.m.albers@nasa.gov)>; Sobchak, Ted C. (GSFC-4590) <[ted.c.sobchak@nasa.gov](mailto:ted.c.sobchak@nasa.gov)>; Gregory, Sean P. (MSFC-ST14) <[sean.p.gregory@nasa.gov](mailto:sean.p.gregory@nasa.gov)>; Hill, Larry (MSFC-ST14)[Consolidated Program Support Services (CPSS PP&C)] <[larry.hill@nasa.gov](mailto:larry.hill@nasa.gov)>
Subject: RE: SNWG MO Program Plan Sign Off & ORR Discussion 
 
Hi Jeanné (et al),
 
I read through the document, which looks great. See comments below, only minor changes recommended in the appendix for signatures. It’s apparent a lot of thought went into planning this. 
 
•	[Section 3.1](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.1ruyx6d0to2l&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7Cd15dd207891d4b4d4dc808db5dfd3bd6%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638207114438336936%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=sC3i00tpAXFrHuDOntYRGo6qtfgU%2BNKi%2FQah3K619Pc%3D&reserved=0) (lists ESDIS and the DAACs as SNWG MO stakeholders) – Read and concur
•	[Section 5.1.2.3](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.7vh1tc7z9f9v&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7Cd15dd207891d4b4d4dc808db5dfd3bd6%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638207114438336936%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Y7HYZqVW8tHz0rvd9xUx4xoSl9IRkHoaIKwUs%2BJnT6s%3D&reserved=0) (Requirement III only) – Read and concur
•	[Section 6.1](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.yo3q9tl74wf7&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7Cd15dd207891d4b4d4dc808db5dfd3bd6%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638207114438493156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RDRpKgDRQCdsPnIv%2F0pAurnXu4Q5w49cW6kzqYaU3U0%3D&reserved=0) (notes that ESDIS supports cost estimation efforts during the Assessment phase) – Read and concur
•	[Section 6.2.1](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.c8kzoiv2i9x0&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7Cd15dd207891d4b4d4dc808db5dfd3bd6%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638207114438493156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qK9rg%2BdOuawFOgaYcuMO%2FYvskEKa2MnrLJBLs1MiKGo%3D&reserved=0) (describes the DAAC selection process) – Read and concur
•	[Section 12.1.3](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.e7vibarxsbv&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7Cd15dd207891d4b4d4dc808db5dfd3bd6%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638207114438493156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KdXX%2BobIC0Gw8ijc81dhvGm6z4uIvGA9IWf%2Bj%2B%2F79PU%3D&reserved=0) (describes the Assessment phase. Mention of ESDIS cost estimation support.) – Read and concur
•	[Section 12.2.2.1](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.sp5ax9onn9pt&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7Cd15dd207891d4b4d4dc808db5dfd3bd6%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638207114438493156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=eY%2BWeqtiUdM5JmaM2bUo5ANzS5YlvrQrH8DCPACHsdU%3D&reserved=0) (re-iterates DAAC selection step and agreement types w/ ESDIS/DAACs) – Read and concur
•	[Section 12.2.2.3](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.2q10ulif3uso&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7Cd15dd207891d4b4d4dc808db5dfd3bd6%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638207114438493156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=D3P1zyFE7O2xlp6qduXIRrIqz7zPT2WoqGpIoUtultw%3D&reserved=0) (Formulation to Implementation Decision Gate review – if data goes to a DAAC, an ESDIS & DAAC representative will be invited to this review. At this point the DAAC selection and any agreements with ESDIS/DAACs should be completed.) – Read and concur
•	[Section 12.2.3.1.4](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.4c3bur2rcgw6&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7Cd15dd207891d4b4d4dc808db5dfd3bd6%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638207114438493156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fZokeaP8058J5%2BNOoyDUYquwScJkQbzxVo3ZCEUUyhI%3D&reserved=0) (describes the ORR – also recommend reading [Section 12.2.3.1.3](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.mh1i02nkpeyr&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7Cd15dd207891d4b4d4dc808db5dfd3bd6%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638207114438493156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aQkXdyquR3j6j90wd890ZFzYfsAiOoadOmtgwAHMGP4%3D&reserved=0) right before) ** this is a key touchpoint we’d like to discuss ASAP   – Read and concur, I went through detail by detail and read a couple times to be certain, also reviewing the relevant sections of NPR 7123.1C 
•	[Section 12.2.4.2](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.ahueog70qipv&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7Cd15dd207891d4b4d4dc808db5dfd3bd6%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638207114438493156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bGHXE8%2FKHw8co5cP7muIXAEawOqhROUOLDwZXTN4DKM%3D&reserved=0) (describes project closeout – if data goes to a DAAC, an ESDIS & DAAC representative will be invited to participate in the closeout review) – Read and concur, through the document is talks about early inclusion, if appropriate, which is much appreciated
•	[Appendix D](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.bzt20h47l9gr&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7Cd15dd207891d4b4d4dc808db5dfd3bd6%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638207114438493156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FcYEKJgRp2S8gWxEtWi6wzWW6vVoUn7L4hZCHIW5AkU%3D&reserved=0) (signature authorities for agreements w/ ESIDS. This list is based on the OPERA IPA/ICDs so please let us know if these are not the correct personnel.) – Read and only suggestion would be to modify in “Reviewer & Signature Authority” column for row 1 (ICD)  add ESDIS Deputy Project Manager – Science Operations.. In row 2 (IPA), add ESDIS Deputy Project Manager – Science Operations and ESDIS Science Data Office Manager. Remove EOSDIS Science Operations Manager. Replace EOSDIS System Manager with ESDIS Missions Systems Manager. I think that’s the only recommended edits in this appendix. This aligns with our revised org roles. 
•	[Appendix F](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.google.com%2Fdocument%2Fd%2F1h61-iNI_-HOII69zEEkuggT-3VKXAvspPRufizM7bao%2Fedit%23heading%3Dh.l0yrhiwbqq3t&data=05%7C01%7Ccherrelle.j.tucker%40nasa.gov%7Cd15dd207891d4b4d4dc808db5dfd3bd6%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C638207114438493156%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3dRJHCaVeibPx2MyhXA5NtiiU847a%2B9%2Be7U5erR0wKY%3D&reserved=0) (DAAC table & re-iterates that ESDIS carries out the DAAC selection process) – Read and looks good
 
 
Best,
Dana
 
 
Dana Ostrenga 
Assistant Project Manager

**Comment by CherrelleTucker** [comment]
From: Jeanné le Roux <jeanne.leroux@nsstc.uah.edu> 
Sent: Wednesday, June 7, 2023 4:05 PM
To: Gregory, Sean P. (MSFC-ST14) <sean.p.gregory@nasa.gov>; Ramachandran, Rahul (MSFC-ST11) <rahul.ramachandran@nasa.gov>; Olofsson, Pontus (MSFC-ST11) <pontus.olofsson@nasa.gov>
Cc: Tucker, Cherrelle J. (MSFC-ST11)[Consolidated Program Support Services] <cherrelle.j.tucker@nasa.gov>
Subject: [EXTERNAL] SNWG Program Plan Signature

Hello all,

Attached is a PDF copy of the SNWG Program Plan ready for your signatures. Please pass around the PDF in this email thread. Once we get the signatures from our office I will pass it along to Cerese. 

(also please let me know if you notice any last minute fixes needed before you sign!)

Thanks!

Jeanné le Roux
Systems Engineer | NASA MSFC [IMPACT](https://earthdata.nasa.gov/esds/impact) 
The University of Alabama in Huntsville
Cramer Research Hall/NSSTC 3079
NASA email: [jeanne.leroux@nasa.gov](mailto:jeanne.leroux@nasa.gov)
